title: Charles Beach, The Next Coder
author: Charles Beach
email: charlescbeach@optonline.net
description: > # this means to ignore newlines until "baseurl:"
  Check out some of my best projects. Hear about what I have to offer the world, and my personal experiences with coding.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
